#!/usr/bin/env node
// Generates the iOS and Android launcher icons from the oto mark.
//
//   node scripts/generate-icons.js
//
// The mark's geometry lives in app/theme/logo.js and its colours in
// app/theme/tokens.js, so the icons always match the in-app OtoLogo.

const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

const logo = require('../app/theme/logo');
const {colors} = require('../app/theme/tokens');

const root = path.resolve(__dirname, '..');
const iosIconDir = path.join(
  root,
  'ios/Eyy/Images.xcassets/AppIcon.appiconset',
);
const androidRes = path.join(root, 'android/app/src/main/res');

const {paper, ink, kaki, tonal} = colors.light;

// The ring is an open arc: the SVG mark draws it as a dashed circle, but
// Android vector drawables have no dash arrays, so compute the arc instead.
const ringArc = () => {
  const {cx, cy, r, dashArray, rotation} = logo.ring;
  const sweep = dashArray[0] / r; // radians
  const start = (rotation * Math.PI) / 180;
  const end = start + sweep;
  const point = a =>
    [cx + r * Math.cos(a), cy + r * Math.sin(a)].map(n => n.toFixed(3));
  const [x1, y1] = point(start);
  const [x2, y2] = point(end);
  const largeArc = sweep > Math.PI ? 1 : 0;
  return `M${x1},${y1} A${r},${r} 0 ${largeArc},1 ${x2},${y2}`;
};

const markSvg = ({ringColor, dotColor}) => {
  const {ring, dot} = logo;
  return (
    `<path d="${ringArc()}" fill="none" stroke="${ringColor}" ` +
    `stroke-width="${ring.strokeWidth}" stroke-linecap="round"/>` +
    `<circle cx="${dot.cx}" cy="${dot.cy}" r="${dot.r}" fill="${dotColor}"/>`
  );
};

// A size×size icon: a background shape with the mark centred at `markRatio`.
const iconSvg = ({size, background, shape, markRatio}) => {
  const markSize = size * markRatio;
  const offset = (size - markSize) / 2;
  const scale = markSize / logo.viewBox;
  const bg = {
    square: `<rect width="${size}" height="${size}" fill="${background}"/>`,
    rounded: `<rect width="${size}" height="${size}" rx="${
      size * 0.22
    }" fill="${background}"/>`,
    circle: `<circle cx="${size / 2}" cy="${size / 2}" r="${
      size / 2
    }" fill="${background}"/>`,
  }[shape];
  return Buffer.from(
    `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}">` +
      bg +
      `<g transform="translate(${offset} ${offset}) scale(${scale})">` +
      markSvg({ringColor: ink, dotColor: kaki}) +
      '</g></svg>',
  );
};

const writePng = async (file, svg, {opaque = false} = {}) => {
  let image = sharp(svg);
  if (opaque) {
    image = image.flatten({background: paper}).removeAlpha();
  }
  await image.png().toFile(file);
};

const generateIos = async () => {
  const contentsFile = path.join(iosIconDir, 'Contents.json');
  const contents = JSON.parse(fs.readFileSync(contentsFile, 'utf8'));

  for (const image of contents.images) {
    const px = parseFloat(image.size) * parseFloat(image.scale);
    image.filename = `icon-${image.size}@${image.scale}.png`;
    // iOS masks the corners itself and rejects icons with alpha.
    await writePng(
      path.join(iosIconDir, image.filename),
      iconSvg({size: px, background: paper, shape: 'square', markRatio: 0.62}),
      {opaque: true},
    );
  }

  fs.writeFileSync(contentsFile, JSON.stringify(contents, null, 2) + '\n');
};

const androidDensities = {
  mdpi: 48,
  hdpi: 72,
  xhdpi: 96,
  xxhdpi: 144,
  xxxhdpi: 192,
};

const generateAndroidLegacy = async () => {
  for (const [density, px] of Object.entries(androidDensities)) {
    const dir = path.join(androidRes, `mipmap-${density}`);
    await writePng(
      path.join(dir, 'ic_launcher.png'),
      iconSvg({size: px, background: paper, shape: 'rounded', markRatio: 0.62}),
    );
    await writePng(
      path.join(dir, 'ic_launcher_round.png'),
      iconSvg({size: px, background: tonal, shape: 'circle', markRatio: 0.55}),
    );
  }
};

// Adaptive icons (API 26+): a 108dp canvas whose inner 66dp circle is
// always visible, so the mark is drawn 50dp wide in the centre.
const generateAndroidAdaptive = () => {
  const markDp = 50;
  const scale = markDp / logo.viewBox;
  const offset = (108 - markDp) / 2;
  const {ring, dot} = logo;
  const dotPath =
    `M${dot.cx - dot.r},${dot.cy} ` +
    `a${dot.r},${dot.r} 0 1,0 ${dot.r * 2},0 ` +
    `a${dot.r},${dot.r} 0 1,0 ${-dot.r * 2},0`;
  const vector = (
    ringColor,
    dotColor,
  ) => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate-icons.js; do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <group
        android:translateX="${offset}"
        android:translateY="${offset}"
        android:scaleX="${scale}"
        android:scaleY="${scale}">
        <path
            android:pathData="${ringArc()}"
            android:strokeColor="${ringColor}"
            android:strokeWidth="${ring.strokeWidth}"
            android:strokeLineCap="round" />
        <path
            android:pathData="${dotPath}"
            android:fillColor="${dotColor}" />
    </group>
</vector>
`;

  const drawable = path.join(androidRes, 'drawable');
  fs.mkdirSync(drawable, {recursive: true});
  fs.writeFileSync(
    path.join(drawable, 'ic_launcher_foreground.xml'),
    vector(ink, kaki),
  );
  fs.writeFileSync(
    path.join(drawable, 'ic_launcher_monochrome.xml'),
    vector('#000000', '#000000'),
  );

  fs.writeFileSync(
    path.join(androidRes, 'values/ic_launcher_background.xml'),
    `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate-icons.js; do not edit by hand. -->
<resources>
    <color name="ic_launcher_background">${tonal}</color>
</resources>
`,
  );

  const adaptive = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate-icons.js; do not edit by hand. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
`;
  const anydpi = path.join(androidRes, 'mipmap-anydpi-v26');
  fs.mkdirSync(anydpi, {recursive: true});
  fs.writeFileSync(path.join(anydpi, 'ic_launcher.xml'), adaptive);
  fs.writeFileSync(path.join(anydpi, 'ic_launcher_round.xml'), adaptive);
};

(async () => {
  await generateIos();
  await generateAndroidLegacy();
  generateAndroidAdaptive();
  console.log('Generated iOS and Android launcher icons.');
})().catch(error => {
  console.error(error);
  process.exit(1);
});
